language: python

python:
  - "3.6"

addons:
  - firefox: latest

install:
  - pip install -r requirements.txt

secure: "Jfpz+tqtnBARUwb6uDBlzcF1yC1e02uKToduI8VtUUu/1i4Eomh5LcSKa0w6b8w9IKCZh9hMnTmoPkZrgx9XdkN2qJIWfY01Vqa2Rh1qNTtkasywqkpLa7UzFUUrwGJyqBcAtbRF23YpbABP5mpvmwQL8Xp1PCSNkqRRLZH/R56wPnRJKha8CrdjeYN1mK7uiCh+MK/cTgwPH0nuVNbrGlhDekm7PP29DJaCUNEPvlMf5vdFpuaL7bkYsROf5tLuRoOqQ5m7VUGF1fzLaJtMwlepRyz/HhVEEBbDMsIdGlk/QizngF+hvmLhC4m4VvcEYetb9Ec5XHFAlXAPhqYc19EY8o2LdnvMuU1bnR8zUZ74T4FYlj9SNEua5Ozb0VJLAkFuc7ZYpWX3QxR0FETj3P9xFiMlV3ixFFlErxDHYqHHNBsSOTHE9qLAhRJGvCqNUuQhglo/0ouN+UCAavA9Rp1JAHJoVIy6YbVHFVcF99fQboqJwkzpSs8G2liklu07uLE276uxMjdPYsTL9+e1Zcr3TKwxV8lgBH4iufW3xQfFYz+wQ7WjoeCBbzSpZIBpb7scc9m6M6a+EBJ1CbtnhLIsmhIZWXLWO9qyxVwiTndT9cm8kgtjuoXqMUv3fJstsChlIAPGe8afjrdRn89QAKeFkq547tCtqU2/ZnMNanI="

before_script:
  - sudo service postgresql start
  - psql -c "CREATE DATABASE ocr_petitbeurre;" -U postgres -p 5432
  - pwd
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux32.tar.gz
  - tar -xzvf geckodriver-v0.29.1-linux32.tar.gz

script:
  - ./manage.py migrate
  - ./manage.py test tests.unit.food.tests_units_food tests.unit.favorite.tests_units_favorite tests.unit.profile.tests_units_profile tests.integration.search.tests_search_integration tests.functional.test_saved_food.tests_saved_food
