# Generated by Django 3.1 on 2020-08-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedProduct',
        ),
    ]
