# Generated by Django 3.1 on 2020-08-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200830_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(
                default='https://world.openfoodfacts.org/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(
                default='https://blog.rahulbhutani.com/wp-content/uploads/2020/05/Screenshot-2018-12-16-at-21.06.29.png'),
        ),
    ]
